server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: lt-monitor-server

# 日志配置
logging:
  level:
    org.xi.lt: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
