<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.xi.lt</groupId>
    <artifactId>lt-monitor</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>LT-Monitor</name>
    <description>LT一站式Java应用监控&amp;诊断平台</description>

    <modules>
        <module>lt-common</module>
        <module>lt-agent</module>
        <module>lt-server-apm</module>
        <module>lt-agent-test</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <compiler.version>1.8</compiler.version>
        <grpc.version>1.51.0</grpc.version>
        <protobuf.version>3.21.7</protobuf.version>
    </properties>

    <build>
        <finalName>lt-monitor</finalName>
    </build>
</project>
