<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.xi.lt</groupId>
    <artifactId>lt-monitor</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>LT-Monitor</name>
    <description>LT一站式Java应用监控&amp;诊断平台</description>

    <modules>
        <module>lt-common</module>
        <module>lt-agent</module>
        <module>lt-server-apm</module>
        <module>lt-monitor-agent-test</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <compiler.version>1.8</compiler.version>
        <grpc.version>1.51.0</grpc.version>
        <protobuf.version>3.21.7</protobuf.version>
    </properties>

    <build>
        <finalName>lt-monitor</finalName>
        <plugins>
            <!-- Clean 插件：清理 packages 目录下的插件文件夹 -->
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <filesets>
                        <!-- 删除 plugins 文件夹 -->
                        <fileset>
                            <directory>${project.basedir}/packages/plugins</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                        <!-- 删除 boot-plugins 文件夹 -->
                        <fileset>
                            <directory>${project.basedir}/packages/boot-plugins</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                        <!-- 删除 reporter 文件夹 -->
                        <fileset>
                            <directory>${project.basedir}/packages/reporter</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                        <!-- 删除 packages 文件夹下的jar -->
                        <fileset>
                            <directory>${project.basedir}/packages</directory>
                            <includes>
                                <include>*.jar</include>
                            </includes>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
