<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>lt-server-apm</artifactId>
        <groupId>org.xi.lt</groupId>
        <version>1.0.0</version>
    </parent>
    <artifactId>lt-domain</artifactId>
    <packaging>jar</packaging>
    <name>LT-Domain</name>
    <description>LT-Monitor 领域层（领域模型、领域仓储接口）</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <compiler.version>1.8</compiler.version>
    </properties>

    <dependencies>
        <!-- 公共模块依赖 -->
        <dependency>
            <groupId>org.xi.lt</groupId>
            <artifactId>lt-common</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>lt-domain</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${compiler.version}</source>
                    <target>${compiler.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
