<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.xi.lt</groupId>
        <artifactId>lt-monitor-server-stream</artifactId>
        <version>1.0.0</version>
    </parent>
<!--    <artifactId>lt-stream-servlet</artifactId>-->
    <artifactId>lt-servlet-stream</artifactId>
    <packaging>jar</packaging>
    <name>lt-stream-servlet</name>
    <url>http://www.ltmonitor.net</url>

    <modules>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <compiler.version>1.8</compiler.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.xi.lt</groupId>
            <artifactId>lt-monitor-server-core</artifactId>
            <version>${lt-server-version}</version>
        </dependency>
    </dependencies>
    <build>
        <finalName>lt-stream-servlet-${lt-server-version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
