@startuml
skinparam backgroundColor white
skinparam handwritten false
skinparam shadowing false

:PlantUmlClassDiagramGenerator;
-->:PlantUmlClassDiagramGenerator.generatePlantUml;
-->:PlantUmlClassDiagramGenerator.generateClassDefinition;
-->:PlantUmlClassDiagramGenerator.generateRelationship;
-->:PlantUmlClassDiagramGenerator.getVisibilitySymbol;
-->:PlantUmlClassDiagramGenerator.getClassId;
-->:PlantUmlClassDiagramGenerator.escapeLabel;
-->:PlantUmlClassDiagramGenerator.saveToFile;
-->:plantuml.append;
-->:plantuml.append;
-->:plantuml.append;
-->:plantuml.append;
-->:plantuml.append;
-->:plantuml.append;
-->:plantuml.append;
-->:PlantUmlClassDiagramGenerator.generateClassDefinition;
@enduml
